server:
  port: 8091
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:13306/demo?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: password
  thymeleaf:
    cache: false #关闭模板缓存。
  output:
    ansi:
      enabled: ALWAYS #使用彩色日志输出，正式环境去除