server:
  port: 8091
spring:
  datasource:
    url: jdbc:mysql://10.11.20.8:13001/questionnaire?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456